name: Fastboot Recovery Patcher

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  patch-recovery:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install git wget lz4 tar openssl python3 -y

      # Este enlace de WeTransfer no es un enlace directo, necesitarás un enlace válido
      - name: Download recovery image
        run: |
          wget https://we.tl/t-MKbgvT5uQT -O recovery.img  # Este enlace no funcionará

      - name: Make patching scripts executable
        run: |
          chmod +x tools/magiskboot  # Cambia la ruta para que apunte a la carpeta 'tools'
          chmod +x patcher-minimal.sh

      # Corre el script de parchado
      - name: Run the patching script
        run: ./patcher-minimal.sh  # Asegúrate de que el script pueda encontrar 'magiskboot'

      # Verifica si el archivo de salida está en la ruta esperada
      - name: List output files
        run: ls -lah output/

      # Sube el archivo parchado
      - name: Upload patched image
        uses: actions/upload-artifact@v4
        with:
          name: Patched Recovery Image
          path: output/output.img
          retention-days: 15
