name: Fastboot Recovery Patcher via URL

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Recovery Image URL'
        default: 'https://we.tl/t-MKbgvT5uQT'
        required: true
        type: string

jobs:
  patch-recovery:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install git wget lz4 tar openssl python3 -y
         
      - name: Download recovery image from URL
        run: |
          wget ${{ github.event.inputs.image_url }} -O recovery.img

      - name: Make patching scripts executable
        run: |
          chmod +x magiskboot
          chmod +x patcher-minimal.sh

      - name: Start patching the recovery image
        run: ./patcher-minimal.sh

      - name: Upload patched recovery image
        uses: actions/upload-artifact@v4
        with:
          path: output/output.img
          name: Patched Recovery Image
          retention-days: 15

      - name: Upload keys used in the patching process
        uses: actions/upload-artifact@v4
        with:
          path: keys/*.*
          name: Patch Keys
          retention-days: 15
