name: Fastboot Recovery Patcher

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  patch-recovery:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install git wget lz4 tar openssl python3 -y

      - name: Download recovery image
        run: |
          wget https://we.tl/t-MKbgvT5uQT -O recovery.img

      - name: Make patching scripts executable
        run: |
          chmod +x magiskboot
          chmod +x patcher-minimal.sh

      - name: Run the patching script
        run: ./patcher-minimal.sh

      - name: Upload patched image
        uses: actions/upload-artifact@v4
        with:
          name: Patched Recovery Image
          path: output/output.img
          retention-days: 15
